# MINIO CONFIGURATION (For Tempo Traces)
minio:
  enabled: true
  mode: standalone
  replicas: 1

  additionalAnnotations: 
    argocd.argoproj.io/sync-wave: "1"
  service:
    annotations:
      argocd.argoproj.io/sync-wave: "1"

  #TODO: move these to sealed secrets
  existingSecret: "minio-auth-secret"

  buckets:
    - name: platform-tempo-traces
      policy: none  
      purge: false

  users:
    - accessKey: "tempo-user"
      existingSecret: "minio-auth-secret"
      existingSecretKey: "tempoPassword"
      policy: "readwrite"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  persistence:
    enabled: true
    storageClass: "gp2"
    size: 10Gi
    accessMode: ReadWriteOnce
    annotations:
      argocd.argoproj.io/sync-wave: "1"

#! DISABLE OTHER STACKS TEMPORARILY
prometheus:
  enabled: false
loki:
  enabled: false
tempo:
  enabled: false
alloy:
  enabled: false
grafana:
  enabled: false