apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgB6c18CxFUCxPMe9mXw7os/3ZpP8iOdgCb43P/RIqdbdoJg5rHfEwVvnf2jMESrpHNRHbsFrFDec8j8Y7QTbuwxZaDmP6t23+knlodReEnDOUxlgYi3UCYMJXOZkgu0Q2O3MUSkDK6umpKSQJ0GtXZDGXFh6+bIUAdL/8Z+9TT4QtJET/n4T63pUoj4oqBOzTfW+qlOj5GSo47LfyV8epV7TjXoj/930wnA8o4DACLYhZFt3hjWxo6eJmHqbr/Q0m7oNgKRuz4iWw/+FmO5lVpsEvDLV/uiw/1a6QI82blZt9BizeaLoIsleqecPKTx1/ASI5qqHd+IX1mfM5jfty1zpKZisaC2S06gF6eabo3uVdJCdQ37eB4bzGzEobRHD2cfOqPV5Hd9WJHZ3DSnVa+ahVlsIMf4EphRM91rAsNyNnHrWmJYMWRUq1qgzJ8FCF+9v82TtjwLxzjn2NCLvS5NTfh+VRrcTepVAr40obmEOLAXRFRYOrchUEKGrUx38Cxjybqg8/3RlNvuQm++fyU8wEWp0Dglzndy8OkIm5b88LNPupAll8BrOFl+OF//bZ6sf8UDkS8dahj62jchA4x5jRPPdtTnNFnV2IhyxVpfRlClGQb5vdXM6Jh9NYpj9Aju4GMblpr8RIDuyUTloAds7ot7Wc1G1d00CaNMxmFQiaQbhdCMA52HFaq7Kn7kz+/DhTNvFw914EIM41/vO7AqeHXKhcAdWI48TUimITMm+bVVGG3xDn5X
  template:
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque