apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-runner-token
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBI6qu0/ebcIG37/gdTE4JnRUkwH/Y8ihAUjDFzOWU5P4R+7diORIWaKeK2dhO+5aKW5jnViuF8tDbcUUsaegLNQGZ0RtZImYwbXGNOVNru13ups2rzsa5HyPX6/JES8AlsFjlv/xUCRZjSwoPbQRlEarlc6atINdYdg0qI40++XiY4YpNY7eXS5HBJWlrwqim+PODJi6VsyhSpzOOdEZVjJr/kaU7EQEJxxj15r7/+NfrfwHIcU38Dp4Vh4U7rwkxItBSLj6K9UAY3Gzo6Im3QV9nLDwpnT+NhuphZOm9p14LKz8EvyiXKMtV0LOvh7N0yz/bxYOloYhVnUnwGO/nEH2dzhdrQmLAJjB+L2GrcvZjssWAdpYpD9aEEJsojuWB/nzfdRvLzDsfQwwX+4SZZbY/LZ7nYpqhxdWMUla3dFN88zqlGHzDxvDXLFEAlE4IAKgCGPM8nFLvjYrp8R9gkC0mKaofWKi2eOoK3dEQ+LAAv6KZvJg6f1kMv08KriA76JNYAJq6XYYCbXu7uPmpWfnRlspn7DtpMaq3B1QuGYZZq0ZdySHWeDQpWCK5f5KqgGBcUjYdaMvWHdeBTmq+w4ywCJ4AinTWO/SLo35dLamhsJB0n4w/V3aFtPjXJ/QLrHC6/pVzr8j/GvKyDDGf2H7iWGYghk3W1jERxyKuQufukDyIif5/0rOHLS2q+63rP6y5eVG2YejHJCYnI9f6KHyNXZ2vi+NJipTGgipaLRqBUehnDZdOC
  template:
    metadata:
      name: github-runner-token
      namespace: actions-runner-system
    type: Opaque