apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-runner-token
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgAcVSg8sTPwmi7z/LO6FFLXDep8X3ELt+f3DbtuWRtE4/a2Gqqjdflh84IHCYUP4rAfj3QblFXVmW1IolrRK5Tk9p6uh7sMD4lGzAulNojQxApfvkl58uKpLuJpKG1eF0oGJzsTbrkZ84BoYvM/62S2rhy7rdb+jFgS4igKzq7V7ArHlEzIb38zdI/bRd4bPG0zOrrEDOMpbFZGEUIaE/tnCVTOUsQiOTvVirULW/PSFjHJSo7455ET0MKczEtlMVWSEHenTUSJn7LlNjNgg3CyX0KWFBQIeICigbRAc6vaqOrnQgYc2T1S+SixJvv5UrB7O/eWxssrmjOVmwatYEScH1VYtRLKlBfT8fFj+sFsrDnIg9HJn6V15MRk/4oBNJvCnnp7b3KhHQ3BF14GqGvPn86/zYUw8cknmiCKHpNySfYIdef2ZypyRSD7Pugf7wVdd0MbtwUSlrcLhFK8PsJi0F8HUBGF4h0hQRzCq6NA7A4x9lTDt4Xp93OHFfSuRnrPaZl09ABjN+roQN/lDxz/Vvgx1jcB4PdlQhyc46FqfnR2rGpUHWs6wAiPZTBw8BMhQDXiK2lfoBvvMHl5ub6Uqolx1zElcmd7/0vRRBtQ62MjGkbEjI7gBYjYjM9mnQ08YOebu7XDT3sTVF/+yqcfrbqdJU1q/wXt+1xv7IPhkSxjX4R/E2At1TIyIIy6IUv5IkEWtTV5u5giV6ZV80UHum0r5VD2mw1jka8fshfIjr/Gl22CnrYq
  template:
    metadata:
      name: github-runner-token
      namespace: actions-runner-system
    type: Opaque