apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-runner-token
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgAeCDF+0nk9elllR2ec3BLyaX3UvW2ylA8zoHwaQmIp5g8GAngP6bOxmEc77PmUhslAfIs49B+d9KWggIfY7FbMfOBN7blZXfazpBuRTahNpc8BHpUlTtwWYruA4KxLaTOkP17EPKeKdY/13yujxHVEk70w22ISDwqs0JfWBJozZxk2GVum+tXDoIIuTsYDFgXDdpocrMvGY8xsVZHt/fbj20ggMZ+P+YW84lbXiE/p8oqexym6L6ilI5vQde1FZCQ7D0NSEBGlaWKQdXWwc3qDYtXIfYgVwf6rcgRVc2/z0QsBwvF5knydhfOoh61elp+nfJ3timpTIpTmopDZH+YBjRqmzhQzR8Yt/mDHIDZs8bCbqBDn5EuCKn76rQCOHLfbdH963G34gJJFqPgF2iDai4f5e2gu3MOdNbGUKqs9TR6wPPjANQeXe/FWkBLA0zw7Gqs1Wa5uOHt3GFqy/o2JHGpz42R8ZVCycOAOJ4JLE5ipxJpRc0Qi4jshbHAjJBVjqMFAFEulbY1Bi9kZGSOGjDS/snN4h65Ovx9e/w93VzCY+X+xjCqp1XQbAUJ1DC4eGrliByaYGjV+QDvx+opanO9EkhqJBa2sQFGprNvgQQqNB39jdPC8/HiBsx6YNG1IHiEJMuVFNybN1tQYK1rka3UILJcbO8l/kmlcGcBJKmdxWd+zMUou9R62LrOxOEaLNkVzIW2OPXCidb639Wox0/iiwUg0FYUvCc391MfxQm1qH9O5Mgeq
  template:
    type: Opaque
    metadata:
      name: github-runner-token
      namespace: actions-runner-system