apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: 'https://github.com/kserve/kserve.git'
    targetRevision: v0.18.0
    path: charts/kserve-resources
    # هنا هنستخدم Kustomize عشان يعمل Patch
    kustomize:
      patches:
        - target:
            kind: ConfigMap
            name: inferenceservice-config
          patch: |-
            - op: replace
              path: /data/ingress
              value: |
                {
                    "enableGatewayApi": false,
                    "kserveIngressGateway": "kserve/kserve-ingress-gateway",
                    "ingressGateway": "istio-system/kubevision-gateway",
                    "knativeLocalGatewayService": "",
                    "localGateway": "knative-serving/knative-local-gateway",
                    "localGatewayService": "knative-local-gateway.istio-system.svc.cluster.local",
                    "ingressClassName": "istio",
                    "ingressDomain": "creative.opik.net",
                    "domainTemplate": "{{ .Name }}.{{ .IngressDomain }}",
                    "urlScheme": "https",
                    "disableIstioVirtualHost": false,
                    "disableIngressCreation": false,
                    "disableHTTPRouteTimeout": false
                }
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true