apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  namespace: platform-apps
  labels:
    app: platform-api
spec:
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      serviceAccountName: api-sa
      containers:
        - name: platform-api
          image: 439328746854.dkr.ecr.us-east-1.amazonaws.com/platform-api:774e7068aa571896afc1fc3433d2b7455c0af22c
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
              name: http
          resources:
            requests:
              cpu: "200m" 
              memory: "512Mi"