apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  namespace: platform-apps
  labels:
    app: platform-api
spec:
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      serviceAccountName: api-sa
      containers:
        - name: platform-api
          image: 439328746854.dkr.ecr.us-east-1.amazonaws.com/platform-api:a9503d75c16c27ebf39dca94249184b757755a11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
              name: http