apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  # 1. ربط المنصة بالدومين بتاعك
  creative.opik.net: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  ingress-class: "gateway-api.ingress.networking.knative.dev"
  default-external-scheme: "https"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: knative-serving
data:
  gateway-api.external-gateway: "kubevision-ingress/kubevision-gateway"
  gateway-api.local-gateway: "kubevision-ingress/kubevision-gateway"
  gateway-api.section-name: "https-wildcard"