apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serving-core.yaml
  - serving-gateway-api.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config-domain
        namespace: knative-serving
      data:
        creative.opik.net: ""

  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config-network
        namespace: knative-serving
      data:
        ingress-class: "gateway-api.ingress.networking.knative.dev"
        default-external-scheme: "https"
        domain-template: "{{.Name}}.{{.Domain}}"
        httpProtocol: "Redirected"

  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config-gateway
        namespace: knative-serving
      data:
        external-gateways: '[{"class": "istio", "gateway": "kubevision-ingress/kubevision-gateway", "service": "kubevision-ingress/kubevision-gateway-istio"}]'
        local-gateways: '[{"class": "istio", "gateway": "kubevision-ingress/kubevision-gateway", "service": "kubevision-ingress/kubevision-gateway-istio"}]'