name: Test ARC Runner

on:
  workflow_dispatch:

jobs:
  test-our-setup:
    runs-on: platform-runner
    
    steps:
      - name: Say Hello from Kubernetes
        run: echo "Hello from the inside of KubeVision EKS Cluster!"
        
      - name: Checking the environment
        run: pwd && whoami